configName: development
folderName: ''
format_version: v1.0
frameworkPath: ../../../Harmony3
processor: PIC32MX250F256H
projectName: ''
settings:
  PackageFilter: csp;dev_packs;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX250F256H.atdf
