configName: development
folderName: ''
format_version: v1.0
frameworkPath: ../../../Harmony3
processor: PIC32MX250F256H
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;crypto;csp;csp_apps_pic32mk;csp_apps_pic32mx;dev_packs;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX250F256H.atdf
